headline_rates:
  default: 0.1
  '5700': 0
  '1220': 0
  '2010': 0
  '5880': 0
  '4120': 0
  '4330': 0
  '4231': 0
  '4870': 0
  '4791': 0
  '4910': 0
  '4351': 0
  '4099': 0
  '4470': 0
  '4050': 0
  '4279': 0
  '4280': 0
  '4840': 0
  '4370': 0
  '4190': 0
  '4759': 0
  '4490': 0
  '4510': 0
  '4239': 0
  '4730': 0
  '4210': 0
  '4550': 0
  '4710': 0
  '4850': 0
  '4359': 0
  '4792': 0
  '4700': 0
  '4010': 0
  '6021': 0
  '5800': 0
  '5590': 0
  '3370': 0
  '3010': 0
  '3330': 0
  '2230': 0
  '2050': 0
  '2150': 0
  '2190': 0
  '2250': 0
  '2110': 0
  '2470': 0
  '5250': 0
  '5081': 0
  '5110': 0
  '5230': 0
  '7140': 0
product_rates: []
product_country_rates: []
